### ISSUE TITLE
Are the docs up to date? 

### ISSUE THREAD

**Issue by jmhimara** [diku-dk/linalg#7]
Just curious if the docs on the website are up to date? (https://futhark-lang.org/pkgs/github.com/diku-dk/linalg/0.4.3/index.html)

For instance, in the docs there is no entry for a function that computes the eigenvalues of a square matrix, but I am seeing it in the source code (https://github.com/diku-dk/linalg/blob/02ac17238bda19049b037fd7e5e49453afef1b59/lib/github.com/diku-dk/linalg/linalg.fut#L86). 

Or is this function still work in progress?

**Comment by athas** [comment]
The infrastructure that builds the docs, [futhark-docbot](https://github.com/diku-dk/futhark-docbot), is sadly not well setup (I'm the one who did it, and I'm not good at infrastructure).  I kicked off a manual run, so docs for the newest linalg should be available soon.

**Comment by athas** [comment]
Docs for the newest versions of all packages should be built now.
